### ISSUE TITLE
project id not found in projects.json

### ISSUE THREAD

**Issue by mittermichal** [eggplantcx/fah-rp#1]
Hello,
I'm running project with id 11777, but its not in the projects.json
so I get: Cannot read property 'id' of undefined
Verify Folding@home is running
Terminating Program
I guess you have to update it automatically

**Comment by mittermichal** [comment]
I am Kimi|AHK from that discord support thread btw :D

**Comment by mittermichal** [comment]
awesome! it works now :+1:

**Comment by treevar** [comment]
Glad it's working, thanks for reporting the issue
