### ISSUE TITLE
Rich Presence not working

### ISSUE THREAD

**Issue by abgrac** [eggplantcx/fah-rp#2]
Hello friend, first of all, nice initiative!

I've already installed Node LTS and run getModules.bat, then start.bat. All with Admin previleges.
But unfortunately my Discord is not clutching the console start.bat. Although it is running and logging correctly.

![console](https://user-images.githubusercontent.com/7785230/79051614-72bfa900-7c07-11ea-9fa2-f0217b49185c.png)

Did I miss something?
Thank you in advance!

**Comment by treevar** [comment]
Hi, in Discord can you go to **settings > game activity** and and make sure "Display currently running game as a status message." is on

**Comment by abgrac** [comment]
Hey eggplant,
Actually it is already on. I already use Rich Presence with quite a lot games and some other custom stuff, like VSCode and Unity. But strangely with your node implementation is does not engage automatically, neither I can select it as a custom running executable. Despite it's running ok.

Win10 64-bit updated.
Intel i5.
GTX 1070.
Discord updated.
NodeJS Latest LTS.
F@h v7.5.1 (latest) in 32-bit (the only client option right)

**Comment by treevar** [comment]
I have basically the same setup as you and I've had multiple people test it and it worked fine, I have no idea why it's not working, maybe try redownloading it, otherwise I have no idea

**Comment by treevar** [comment]
Closed, as version referenced is no longer functioning
