### ISSUE TITLE
getModules.bat giving an error

### ISSUE THREAD

**Issue by Saltssaumure** [eggplantcx/fah-rp#3]
Hey there, this sounds like an excellent idea but I can't figure out how to get it to work. I ran getModules.bat, Discord, and F@H as admin.

CPU: Ryzen 5 2600X
RAM: 16GB
OS: Windows 10 Home

Discord version: Latest (0.0.306)
F@H version: Latest (7.6.9)
Node.js version: Latest (12.16.2 64-bit)

Debug log:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'discord-rich-presence'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose npm-session c9877b180f8ba730
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/discord-rich-presence 614ms (from cache)
8 silly pacote version manifest for discord-rich-presence@0.0.8 fetched in 628ms
9 timing stage:loadCurrentTree Completed in 660ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 27ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule discord-rich-presence@0.0.8 checking installable status
17 silly removeObsoleteDep removing discord-rich-presence@0.0.8 from the tree as its been replaced by a newer version or is no longer required
18 silly removeObsoleteDep removing discord-rpc@github:discordjs/rpc#cfddf66c372abe430a284ff3ea885e8cc0477f99 from the tree as its been replaced by a newer version or is no longer required
19 silly removeObsoleteDep removing node-fetch@2.6.0 from the tree as its been replaced by a newer version or is no longer required
20 silly removeObsoleteDep removing ws@7.1.2 from the tree as its been replaced by a newer version or is no longer required
21 silly removeObsoleteDep removing async-limiter@1.0.1 from the tree as its been replaced by a newer version or is no longer required
22 silly fetchPackageMetaData error for discord-rpc@github:discordjs/rpc Error while executing:
22 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/discordjs/rpc.git
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData spawn git ENOENT
23 timing stage:rollbackFailedOptional Completed in 1ms
24 timing stage:runTopLevelLifecycles Completed in 740ms
25 silly saveTree fah-rp@1.0.0
25 silly saveTree +-- axios@0.19.2
25 silly saveTree | `-- follow-redirects@1.5.10
25 silly saveTree |   `-- debug@3.1.0
25 silly saveTree |     `-- ms@2.0.0
25 silly saveTree +-- cheerio@1.0.0-rc.3
25 silly saveTree | +-- css-select@1.2.0
25 silly saveTree | | +-- boolbase@1.0.0
25 silly saveTree | | +-- css-what@2.1.3
25 silly saveTree | | +-- domutils@1.5.1
25 silly saveTree | | | +-- dom-serializer@0.1.1
25 silly saveTree | | | | +-- domelementtype@1.3.1
25 silly saveTree | | | | `-- entities@1.1.2
25 silly saveTree | | | `-- domelementtype@1.3.1
25 silly saveTree | | `-- nth-check@1.0.2
25 silly saveTree | +-- dom-serializer@0.1.1
25 silly saveTree | +-- entities@1.1.2
25 silly saveTree | +-- htmlparser2@3.10.1
25 silly saveTree | | +-- domhandler@2.4.2
25 silly saveTree | | +-- inherits@2.0.4
25 silly saveTree | | `-- readable-stream@3.6.0
25 silly saveTree | |   +-- string_decoder@1.3.0
25 silly saveTree | |   | `-- safe-buffer@5.2.0
25 silly saveTree | |   `-- util-deprecate@1.0.2
25 silly saveTree | +-- lodash@4.17.15
25 silly saveTree | `-- parse5@3.0.3
25 silly saveTree |   `-- @types/node@13.11.1
25 silly saveTree `-- discord-rich-presence@0.0.8
26 verbose stack Error: spawn git ENOENT
26 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
26 verbose stack     at onErrorNT (internal/child_process.js:469:16)
26 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
27 verbose cwd O:\Downloads\fah-rp-master\fah-rp-master
28 verbose Windows_NT 10.0.17763
29 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "discord-rich-presence"
30 verbose node v12.16.2
31 verbose npm  v6.14.4
32 error code ENOENT
33 error syscall spawn git
34 error path git
35 error errno ENOENT
36 error enoent Error while executing:
36 error enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/rpc.git
36 error enoent
36 error enoent
36 error enoent spawn git ENOENT
37 error enoent This is related to npm not being able to find a file.
38 verbose exit [ 1, true ]

**Comment by treevar** [comment]
you may need to install git, if you do have it installed verify that it is in your PATH

**Comment by treevar** [comment]
Closed, as version referenced is no longer functioning
