### ISSUE TITLE
Bad Session ID on start.bat

### ISSUE THREAD

**Issue by kamisenpai** [eggplantcx/fah-rp#7]
So I seem to get this error when starting the start.bat script. Any idea what could be causing it?

`Got SID: ****************************** G
Bad Session ID
Attempting to get sid...`

Edit: from what I can gather the 127.0.0.1/7395/api link doesn't exist anymore?

**Comment by treevar** [comment]
Fixed in e7030ebbc372a5b75a2e5b89c98313f84355b1df
